[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
endcoin = "7vgyfejeG9Yt75gvmBY8xQPviAo9S4zVPK5o5cHkJXiN"

[programs.devnet]
endcoin = "7vgyfejeG9Yt75gvmBY8xQPviAo9S4zVPK5o5cHkJXiN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-0 = "yarn run ts-node deployment/00_generate_keypairs.ts"
deploy-1 = "yarn run ts-node deployment/create-amm.ts"
deploy-2 = "yarn run ts-node deployment/02_create-metadata.ts"
deploy-3 = "yarn run ts-node deployment/create-pool.ts"



[test.validator]
url = "https://api.mainnet-beta.solana.com"
