[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
endcoin = "Dm8CMAiXHEcpxsN1p69BGy1veoUvfTbCgjv9eiH3U7eH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/andrew/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "yarn run ts-node deployment/create-amm.ts"
[test.validator]
url = "https://api.mainnet-beta.solana.com"
